package cofr;

import java.util.HashMap;
import users.*;

public class Request {
	private CallerI caller;
	private HashMap<String, String> params;
	private User user;

	public Request() {
		this.params = new HashMap<String, String>();
	}

	public Object getCaller() {
		return caller;
	}

	public void setCaller(CallerI caller) {
		this.caller = caller;
	}

	public HashMap<String, String> getParams() {
		return params;
	}

	public void addParam(String key, String value) {
		params.put(key, value);
	}

	public void setParams(HashMap<String, String> params) {
		this.params = params;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	public User getUser(){
		return this.user;
	}

	public String getParam(String key) {
		return params.containsKey(key) ? params.get(key) : null;
	}

	@Override
	public String toString() {
		String[] str = { "Request target: ", this.params.get("target"), "Request generated by: ",
				this.caller == null ? "null" : this.caller.getName(), "Request params: " + this.params };
		return String.join("\n..", str);
	}

}
